### ISSUE TITLE
Fix /auth get issue

### ISSUE THREAD

**Issue by Owez** [Owez/authrio#6]
Python api cant seem to get with /auth, returning code 404 with no text info

**Comment by Owez** [comment]
fixed 404, now giving cryptic 400:

```none
could not parse uuid
Traceback (most recent call last):
  File "blah.py", line 14, in <module>
    org.auth(key)
  File "/home/owen/Projects/rust/authrio/py/authrio.py", line 376, in auth
    raise BadConnection(resp)
authrio.BadConnection: <Response [400]>
```
